version: '3.8'

services:
  web:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=ctf_user
      - MYSQL_PASSWORD=ctf_password
      - MYSQL_DATABASE=ctf_db
      - ./src/init.sh:/docker-entrypoint-initdb.d/init.sh
    restart: unless-stopped

  db:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=ctf_db
      - MYSQL_USER=ctf_user
      - MYSQL_PASSWORD=ctf_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/init.sh:/docker-entrypoint-initdb.d/init.sh
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: 